In [1]:
import numpy as np


In [7]:
a = np.random.randn(5,1)
print(a)

[[ 0.22075708]
 [-0.52366955]
 [ 1.59583291]
 [-0.04637756]
 [ 0.85335842]]


In [5]:
print(a.shape)

(5,)


In [6]:
print(a.T)

[ 0.93095234  1.00022693 -0.21159114 -0.77646471 -0.56081326]


In [8]:
print(np.dot(a, a.T))

[[  4.87336904e-02  -1.15603763e-01   3.52291420e-01  -1.02381757e-02
    1.88384917e-01]
 [ -1.15603763e-01   2.74229797e-01  -8.35689099e-01   2.42865177e-02
   -4.46877819e-01]
 [  3.52291420e-01  -8.35689099e-01   2.54668267e+00  -7.40108417e-02
    1.36181745e+00]
 [ -1.02381757e-02   2.42865177e-02  -7.40108417e-02   2.15087838e-03
   -3.95766841e-02]
 [  1.88384917e-01  -4.46877819e-01   1.36181745e+00  -3.95766841e-02
    7.28220591e-01]]


In [9]:
a = np.random.rand(10)

In [10]:
print(a.reshape(2, 5))

[[ 0.7487116   0.16780465  0.82598197  0.85958723  0.43888893]
 [ 0.24039758  0.16517728  0.22033699  0.25561313  0.89838006]]


In [11]:
A = np.random.randn(4, 3)
B = np.sum(A, axis=1, keepdims = True)

In [12]:
B.shape

(4, 1)

In [13]:
pwd

'C:\\Users\\Tianran\\Documents\\Workspace\\DeepLearning\\DL.ai'