In [7]:
import numpy as np
import time

In [8]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [15]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vertorized Version: " + str(1000*(toc - tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("Non Vertorized Version: " + str(1000*(toc - tic)) + "ms")

249814.017353
Vertorized Version: 1.0018348693847656ms
249814.017353
Non Vertorized Version: 776.4286994934082ms


In [16]:
v = np.array([1, 2, 3, 4])

In [17]:
u = np.exp(v)
u

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [19]:
np.exp(2)

7.3890560989306504

In [23]:
a = np.random.rand(10)

array([ 0.7692565 ,  0.84609254,  0.32624194,  0.10592406,  0.72294642,
        0.35868497,  0.43019184,  0.28365592,  0.27206445,  0.26460247])